config/routes.rb
BlogBangaloreruby::Application.routes.draw do
  match 'author/:id' =>'posts#by_author', :as => :posts_by_author
  match 'month/:year/:month' =>'posts#by_month', :as => :posts_by_month
  match '/atom' => 'posts#index', :as => :atom_feed, :format => :atom
  
  resources :feeds

  root :to => 'posts#index'
end

app/models/feed.rb
# == Schema Information
require 'atom'
require 'net/http'
require 'uri'
require 'rss/1.0'
require 'rss/2.0'
require 'open-uri'


class Feed < ActiveRecord::Base
  has_many :posts, :dependent => :delete_all
  scope :by_most_recent_post, includes(:posts).merge(Post.most_recent_first)
  scope :by_author, order(:author)


  after_create { |feed| feed.get_latest}

  def twitter_username= twitter_username
    twitter_username = twitter_username.sub('@', '') if twitter_username
    super(twitter_username)
  end

  def twitter_username_with_at_sign
    "@#{twitter_username}" unless twitter_username.blank?
  end

  def to_param
    "#{id}-#{author.gsub(' ', '_')}"
  end

  def get_feed
    uri = URI.parse(feed_url)
    uri.read
  end

  def get_posts_from_atom atom_xml
    feed = Atom::Feed.new(atom_xml)
    feed.entries.each do |entry|
      if entry.published
        link = entry.links.detect {|l| l.rel == 'alternate'}
        content = entry.summary || entry.content
        content = content.value if (content.mime_type == 'text/html') && content.respond_to?(:value)
        create_post(:contents=>content, :url=>link.href, :title=>entry.title, :published=>entry.published.to_s(:db), :updated=>entry.updated.to_s(:db))
      end
    end unless false
    return false if feed.entries.blank?
    update_attributes(:name=>feed.title, :url=>feed.links.detect{|link| link.type=='text/html'}.href) unless name && url
    return true
  end

  def get_posts_from_rss rss_xml
    rss = RSS::Parser.parse(rss_xml, false)
    rss.items.each { |entry|
      create_post(:contents=>entry.description, :url=>entry.link, :title=>entry.title, :published=>entry.date.to_formatted_s(:db), :updated=>entry.date.to_formatted_s(:db))
    }
    return false if rss.items.blank?
    update_attributes(:name=>rss.channel.title, :url=>rss.channel.link) unless name && url
    return true
  end

  def create_post params
    params.merge!(:feed_id=>id)
    existing_post = Post.find_by_url(params[:url])
    if existing_post
      existing_post.update_attributes(params)
    else
      Post.create(params)
    end
  end


  def get_latest
    puts "getting feed for #{author}-#{name}"
    xml = get_feed
    got_atom_posts = get_posts_from_atom xml
    get_posts_from_rss xml unless got_atom_posts
  end

  def self.update_all
    Feed.all.each do |feed|
      begin
        feed.get_latest
      rescue 
        puts "Error updating feed for #{feed.inspect} #{$!}"
      end
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  scope :most_recent_first, order('posts.published desc')
  scope :by_date_published, lambda {|date| where(["published <= ? and published >= ?", date.end_of_month, date.beginning_of_month]) }

  belongs_to :feed

  def Post.activity_by_date
    activity = Post.count(:published, :group=>"published") #date_format(published, '%Y-%c')")
    activity_by_date = {}
    activity.each do |row|
      # raise row[0].year.inspect
      year,month = row[0].year, row[0].month #row[0].split '-'
      activity_for_this_year = activity_by_date[year.to_i] ||= {}
      activity_for_this_year[month.to_i] = row[1]
    end
    activity_by_date
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_filter :authenticate

  # GET /feeds
  # GET /feeds.xml
  def index
    @feeds = Feed.by_author

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.xml
  def show
    @feed = Feed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.xml
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.xml
  def create
    @feed = Feed.new(params[:feed])

    respond_to do |format|
      if @feed.save
        flash[:notice] = 'Feed was successfully created.'
        format.html { redirect_to(@feed) }
        format.xml  { render :xml => @feed, :status => :created, :location => @feed }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.xml
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        flash[:notice] = 'Feed was successfully updated.'
        format.html { redirect_to(@feed) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.xml
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to(feeds_url) }
      format.xml  { head :ok }
    end
  end
  
  protected
  def authenticate
    authenticate_or_request_with_http_basic do | user_name, password|
      (user_name == ENV['BLOG_USERNAME']) && (password == ENV['BLOG_PASSWORD'])
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  def index
    @posts = Post.most_recent_first.all(:limit=>30)
    nav_info
    
    respond_to do |format|
      format.html
      format.atom
    end
  end

  # GET /posts/by_author
  def by_author
    @posts = Post.most_recent_first.find_all_by_feed_id(params[:id])
    nav_info
    render :action=>:index
  end

  # GET /posts
  def by_month
    @posts = Post.most_recent_first.by_date_published(Date.strptime("#{params[:year]}-#{params[:month]}", "%Y-%m"))
    nav_info
    render :action=>:index
  end

protected
  def nav_info
    @active_feeds = Feed.by_most_recent_post
    @activity_by_date = Post.activity_by_date
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/feeds/_form.html.haml
= form_for @feed do |f|
  -if @feed.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:"
      %ul
        - @feed.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :feed_url
    = f.text_field :feed_url
  .field
    = f.label :author
    = f.text_field :author
  .field
    = f.label :twitter_username
    = f.text_field :twitter_username
  .actions
    = f.submit 'Save'

app/views/feeds/edit.html.haml
%h1 Editing feed

= render 'form'

= link_to 'Show', @feed
\|
= link_to 'Back', feeds_path

app/views/feeds/index.html.haml
%h1 Listing feeds

%table
  %tr
    %th Url
    %th Name
    %th Feed url
    %th Author
    %th Twitter username
    %th
    %th
    %th

  - @feeds.each do |feed|
    %tr
      %td= feed.url
      %td= feed.name
      %td= feed.feed_url
      %td= feed.author
      %td= feed.twitter_username
      %td= link_to 'Show', feed
      %td= link_to 'Edit', edit_feed_path(feed)
      %td= link_to 'Destroy', feed, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Feed', new_feed_path

app/views/feeds/new.html.haml
%h1 New feed

= render 'form'

= link_to 'Back', feeds_path

app/views/feeds/show.html.haml
%p#notice= notice

%p
  %b Url:
  = @feed.url
%p
  %b Name:
  = @feed.name
%p
  %b Feed url:
  = @feed.feed_url
%p
  %b Author:
  = @feed.author
%p
  %b Twitter username:
  = @feed.twitter_username

= link_to 'Edit', edit_feed_path(@feed)
\|
= link_to 'Back', feeds_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bangalore Ruby Talk</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <link rel="alternate" type="application/atom+xml" title="BangaloreRuby Blog - Atom" href="<%= atom_feed_url %>" />
  <%= csrf_meta_tags %>

  <!--[if lt IE 7.]>
    <script defer type="text/javascript" src="/javascripts/pngfix.js"></script>
  <![endif]-->
</head>
<body>

  <div id="band"></div>
  <div id="wrapper">
    <%= render :partial => "shared/header" %>
    <%= yield %>
    <%= render :partial => "shared/footer" %>
  </div>

</body>
</html>

app/views/posts/_archive.html.haml
%h2 Archive
%ul
  - @activity_by_date.keys.sort.reverse.each do |year|
    %li= year
    %ul
      - @activity_by_date[year].keys.sort.reverse.each do |month|
        %li= link_to(Date::MONTHNAMES[month], posts_by_month_url(year, month))

app/views/posts/_whos_talking.html.haml
%h2 Who is talking?
%ul
  - @active_feeds.each { |feed|
  %li= link_to(feed.author, posts_by_author_url(feed))
  - }

app/views/posts/index.html.haml
#site
  .right.right_column
    = render :partial=>'posts/whos_talking'
    %br/
    %br/
    = render :partial=>'posts/archive'
  .left.left_column
    - for post in @posts
      %h1= link_to post.title, post.url
      %h2
        = distance_of_time_in_words(Time.now, post.published)
        ago | #{link_to "#{post.feed.author}: #{post.feed.name}", post.feed.url}
      %p.content= post.contents.html_safe
      .clear
  .clear

app/views/shared/_footer.html.erb
<div id="footer" class="clear">
  Copyright <%= Time.now.year %>
</div>



<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-19927948-8");
pageTracker._trackPageview();
</script>

app/views/shared/_header.html.erb
<h1 class='left'>Bangalore Ruby</h1>
<div class="clear"></div>